// <auto-generated />
using System;
using LeaseBridge.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaseBridge.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260508175428_FinalInitialSetup")]
    partial class FinalInitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("AmenityId")
                        .HasName("PK__Amenitie__842AF50BC6F1CC26");

                    b.HasIndex(new[] { "Name" }, "UQ__Amenitie__737584F62D4066A9")
                        .IsUnique();

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            Name = "Parking"
                        },
                        new
                        {
                            AmenityId = 2,
                            Name = "Gym"
                        },
                        new
                        {
                            AmenityId = 3,
                            Name = "Pool"
                        },
                        new
                        {
                            AmenityId = 4,
                            Name = "WiFi"
                        });
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId")
                        .HasName("PK__AppUsers__1788CC4C4ADB3655");

                    b.HasIndex(new[] { "IdentityUserId" }, "UQ_AppUsers_IdentityUserId")
                        .IsUnique()
                        .HasFilter("[IdentityUserId] IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ApplicationId")
                        .HasName("PK__Applicat__C93A4C99F7AA0BFA");

                    b.HasIndex("StatusId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.ApplicationStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusId")
                        .HasName("PK__Applicat__C8EE206385352328");

                    b.ToTable("ApplicationStatus", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Submitted"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Screening"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "Approved"
                        },
                        new
                        {
                            StatusId = 4,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDD6B9779A51");

                    b.HasIndex("RequestId");

                    b.HasIndex("TenantId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Lease", b =>
                {
                    b.Property<int>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaseId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("LeaseId")
                        .HasName("PK__Leases__21FA58C114FB33A2");

                    b.HasIndex("StatusId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("Leases");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.LeaseStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusId")
                        .HasName("PK__LeaseSta__C8EE20637552008F");

                    b.HasIndex(new[] { "Name" }, "UQ_LeaseStatus_Name")
                        .IsUnique();

                    b.ToTable("LeaseStatus", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Draft"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Active"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "Expired"
                        },
                        new
                        {
                            StatusId = 4,
                            Name = "Renewal"
                        },
                        new
                        {
                            StatusId = 5,
                            Name = "Terminated"
                        });
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Maintena__32499E7757CAB96A");

                    b.HasIndex("StaffId");

                    b.HasIndex(new[] { "RequestId", "StaffId" }, "UQ_Request_Staff")
                        .IsUnique();

                    b.ToTable("MaintenanceAssignments");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId")
                        .HasName("PK__Maintena__442C64BEB509A6F4");

                    b.HasIndex("RequestId");

                    b.ToTable("MaintenanceAttachments");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Maintena__19093A0BCD2F05BF");

                    b.HasIndex(new[] { "Name" }, "UQ_MaintenanceCategories_Name")
                        .IsUnique();

                    b.ToTable("MaintenanceCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Plumbing"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Electrical"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "HVAC"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "General Maintenance"
                        });
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("RequestId")
                        .HasName("PK__Maintena__33A8517A6EB8F73D");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.HasIndex(new[] { "TicketNumber" }, "UQ_Ticket")
                        .IsUnique();

                    b.HasIndex(new[] { "TicketNumber" }, "UQ__Maintena__CBED06DAB3AAE172")
                        .IsUnique();

                    b.ToTable("MaintenanceRequests");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusId")
                        .HasName("PK__Maintena__C8EE20636D4895EC");

                    b.HasIndex(new[] { "Name" }, "UQ_MaintenanceStatus_Name")
                        .IsUnique();

                    b.ToTable("MaintenanceStatus", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Submitted"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Assigned"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "In Progress"
                        },
                        new
                        {
                            StatusId = 4,
                            Name = "Resolved"
                        },
                        new
                        {
                            StatusId = 5,
                            Name = "Closed"
                        });
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceUpdate", b =>
                {
                    b.Property<int>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("NewStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OldStatusId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("UpdateId")
                        .HasName("PK__Maintena__7A0CF3C55F5D63B3");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("OldStatusId");

                    b.HasIndex("RequestId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("MaintenanceUpdates");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("MaintenanceRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("InApp");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E1255D49916");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("MaintenanceRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<int>("MethodId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A3867B7C952");

                    b.HasIndex("LeaseId");

                    b.HasIndex("MethodId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "TransactionReference" }, "UQ_Transaction")
                        .IsUnique()
                        .HasFilter("[TransactionReference] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PaymentMethod", b =>
                {
                    b.Property<int>("MethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MethodId")
                        .HasName("PK__PaymentM__FC681851F4CF137C");

                    b.HasIndex(new[] { "Name" }, "UQ_PaymentMethods_Name")
                        .IsUnique();

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            MethodId = 1,
                            Name = "Cash"
                        },
                        new
                        {
                            MethodId = 2,
                            Name = "Card"
                        },
                        new
                        {
                            MethodId = 3,
                            Name = "Bank Transfer"
                        },
                        new
                        {
                            MethodId = 4,
                            Name = "BenefitPay"
                        });
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PaymentStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusId")
                        .HasName("PK__PaymentS__C8EE2063B7DD4DC4");

                    b.HasIndex(new[] { "Name" }, "UQ_PaymentStatus_Name")
                        .IsUnique();

                    b.ToTable("PaymentStatus", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Partial"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "Paid"
                        },
                        new
                        {
                            StatusId = 4,
                            Name = "Overdue"
                        });
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PriorityType", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PriorityId")
                        .HasName("PK__Priority__D0A3D0BEAE1C0E68");

                    b.HasIndex(new[] { "Name" }, "UQ_PriorityTypes_Name")
                        .IsUnique();

                    b.ToTable("PriorityTypes");

                    b.HasData(
                        new
                        {
                            PriorityId = 1,
                            Name = "Low"
                        },
                        new
                        {
                            PriorityId = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            PriorityId = 3,
                            Name = "High"
                        });
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PropertyId")
                        .HasName("PK__Properti__70C9A735812141E8");

                    b.HasIndex("ManagerId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SkillId")
                        .HasName("PK__Skills__DFA0918772BE8E6B");

                    b.HasIndex(new[] { "Name" }, "UQ__Skills__737584F651195CDD")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            Name = "Plumbing"
                        },
                        new
                        {
                            SkillId = 2,
                            Name = "Electrical"
                        },
                        new
                        {
                            SkillId = 3,
                            Name = "HVAC"
                        },
                        new
                        {
                            SkillId = 4,
                            Name = "Carpentry"
                        },
                        new
                        {
                            SkillId = 5,
                            Name = "Painting"
                        });
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Size")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UnitId")
                        .HasName("PK__Units__44F5ECB524C2F27E");

                    b.HasIndex("PropertyId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.UnitImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("ImageId")
                        .HasName("PK__UnitImag__7516F70C8FA81AA8");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitImages");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.UnitStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusId")
                        .HasName("PK__UnitStat__C8EE2063A09CE406");

                    b.HasIndex(new[] { "Name" }, "UQ_UnitStatus_Name")
                        .IsUnique();

                    b.ToTable("UnitStatus", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Available"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Reserved"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "Occupied"
                        },
                        new
                        {
                            StatusId = 4,
                            Name = "UnderMaintenance"
                        },
                        new
                        {
                            StatusId = 5,
                            Name = "Pending Inspection"
                        });
                });

            modelBuilder.Entity("LeaseBridge.API.Models.UnitType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TypeId")
                        .HasName("PK__UnitType__516F03B52D43BEAD");

                    b.HasIndex(new[] { "Name" }, "UQ_UnitTypes_Name")
                        .IsUnique();

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Name = "Apartment"
                        },
                        new
                        {
                            TypeId = 2,
                            Name = "Studio"
                        },
                        new
                        {
                            TypeId = 3,
                            Name = "Villa"
                        },
                        new
                        {
                            TypeId = 4,
                            Name = "Office"
                        });
                });

            modelBuilder.Entity("StaffSkill", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("StaffId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("StaffSkills", (string)null);
                });

            modelBuilder.Entity("UnitAmenity", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("UnitId", "AmenityId")
                        .HasName("PK__UnitAmen__ECB743E5CEF7A8AA");

                    b.HasIndex("AmenityId");

                    b.ToTable("UnitAmenities", (string)null);
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaseBridge.API.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Application", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.ApplicationStatus", "Status")
                        .WithMany("Applications")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__Statu__534D60F1");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "Tenant")
                        .WithMany("Applications")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__Tenan__5165187F");

                    b.HasOne("LeaseBridge.API.Models.Unit", "Unit")
                        .WithMany("Applications")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__UnitI__52593CB8");

                    b.Navigation("Status");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetUserToken", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Feedback", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.MaintenanceRequest", "Request")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK_Feedback_Request");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "Tenant")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__Tenant__6754599E");

                    b.Navigation("Request");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Lease", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.LeaseStatus", "Status")
                        .WithMany("Leases")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Leases__StatusId__5629CD9C");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "Tenant")
                        .WithMany("Leases")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__Leases__TenantId__5441852A");

                    b.HasOne("LeaseBridge.API.Models.Unit", "Unit")
                        .WithMany("Leases")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Leases__UnitId__5535A963");

                    b.Navigation("Status");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceAssignment", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.MaintenanceRequest", "Request")
                        .WithMany("MaintenanceAssignments")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Reque__5DCAEF64");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "Staff")
                        .WithMany("MaintenanceAssignments")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Staff__5EBF139D");

                    b.Navigation("Request");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceAttachment", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.MaintenanceRequest", "Request")
                        .WithMany("MaintenanceAttachments")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Reque__58D1301D");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.MaintenanceCategory", "Category")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Categ__59063A47");

                    b.HasOne("LeaseBridge.API.Models.PriorityType", "Priority")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("PriorityId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Prior__59FA5E80");

                    b.HasOne("LeaseBridge.API.Models.MaintenanceStatus", "Status")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Statu__5AEE82B9");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "Tenant")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Tenan__571DF1D5");

                    b.HasOne("LeaseBridge.API.Models.Unit", "Unit")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__UnitI__5812160E");

                    b.Navigation("Category");

                    b.Navigation("Priority");

                    b.Navigation("Status");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceUpdate", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.MaintenanceStatus", "NewStatus")
                        .WithMany("MaintenanceUpdateNewStatuses")
                        .HasForeignKey("NewStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_MU_NewStatus");

                    b.HasOne("LeaseBridge.API.Models.MaintenanceStatus", "OldStatus")
                        .WithMany("MaintenanceUpdateOldStatuses")
                        .HasForeignKey("OldStatusId")
                        .HasConstraintName("FK_MU_OldStatus");

                    b.HasOne("LeaseBridge.API.Models.MaintenanceRequest", "Request")
                        .WithMany("MaintenanceUpdates")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Reque__5BE2A6F2");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "UpdatedByNavigation")
                        .WithMany("MaintenanceUpdates")
                        .HasForeignKey("UpdatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_MU_User");

                    b.Navigation("NewStatus");

                    b.Navigation("OldStatus");

                    b.Navigation("Request");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Notification", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.Application", "Application")
                        .WithMany("Notifications")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("FK__Notificat__Appli__66603565");

                    b.HasOne("LeaseBridge.API.Models.MaintenanceRequest", "MaintenanceRequest")
                        .WithMany("Notifications")
                        .HasForeignKey("MaintenanceRequestId")
                        .HasConstraintName("FK__Notificat__Maint__656C112C");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__6477ECF3");

                    b.Navigation("Application");

                    b.Navigation("MaintenanceRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Payment", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.Lease", "Lease")
                        .WithMany("Payments")
                        .HasForeignKey("LeaseId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__LeaseI__619B8048");

                    b.HasOne("LeaseBridge.API.Models.PaymentMethod", "Method")
                        .WithMany("Payments")
                        .HasForeignKey("MethodId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__Method__628FA481");

                    b.HasOne("LeaseBridge.API.Models.PaymentStatus", "Status")
                        .WithMany("Payments")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__Status__6383C8BA");

                    b.Navigation("Lease");

                    b.Navigation("Method");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Property", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.AppUser", "Manager")
                        .WithMany("Properties")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK_Properties_Manager");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Unit", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK__Units__PropertyI__4E88ABD4");

                    b.HasOne("LeaseBridge.API.Models.UnitStatus", "Status")
                        .WithMany("Units")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Units__StatusId__5070F446");

                    b.HasOne("LeaseBridge.API.Models.UnitType", "Type")
                        .WithMany("Units")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Units__TypeId__4F7CD00D");

                    b.Navigation("Property");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.UnitImage", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.Unit", "Unit")
                        .WithMany("UnitImages")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK__UnitImage__UnitI__55F4C372");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StaffSkill", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK_StaffSkills_Skill");

                    b.HasOne("LeaseBridge.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK__StaffSkil__Staff__5FB337D6");
                });

            modelBuilder.Entity("UnitAmenity", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .IsRequired()
                        .HasConstraintName("FK__UnitAmeni__Ameni__5F7E2DAC");

                    b.HasOne("LeaseBridge.API.Models.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK__UnitAmeni__UnitI__5E8A0973");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AppUser", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Feedbacks");

                    b.Navigation("Leases");

                    b.Navigation("MaintenanceAssignments");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("MaintenanceUpdates");

                    b.Navigation("Notifications");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Application", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.ApplicationStatus", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Lease", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.LeaseStatus", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceCategory", b =>
                {
                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceRequest", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("MaintenanceAssignments");

                    b.Navigation("MaintenanceAttachments");

                    b.Navigation("MaintenanceUpdates");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceStatus", b =>
                {
                    b.Navigation("MaintenanceRequests");

                    b.Navigation("MaintenanceUpdateNewStatuses");

                    b.Navigation("MaintenanceUpdateOldStatuses");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PriorityType", b =>
                {
                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Property", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Unit", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Leases");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("UnitImages");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.UnitStatus", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.UnitType", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
